[package]
name = "Salmon"
version = "0.1.0"
authors = ["roquen4145 <roquen4145@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
